pipeline {
    agent any
    
    tools {
        maven 'M3'
        jdk 'JDK11'
    }
    
    environment {
        AWS_CREDENTIAL_NAME = "awsEcrCredentials"
        REGION = "ap-northeast-2"
        ECR_REPOSITORY = "257307634175.dkr.ecr.ap-northeast-2.amazonaws.com"
        ECR_DOCKER_IMAGE = "${ECR_REPOSITORY}/std04-spring-petclinic"
        ECR_DOCKER_TAG = "1.0"
    }
    
    
    stages {
        stage("git init") {
            steps {
                echo 'Git Init'
                git url:'https://github.com/JafarKim/spring-petclinic.git/',
                branch: 'main', credentialsId: 'gitCredentials'
            }
        }
        stage("build") {
            steps {
                echo 'Build'
                sh 'mvn -Dmaven.test.failure.ignore=true clean package'
            }
        }
        stage("docker image build") {
            steps {  
                echo 'Docker Image Build'
                dir("${env.WORKSPACE}") {
                    sh 'docker build -t std04-spring-petclinic:1.0 .'
                }
            }
        }
        stage ("docker image push") {
            steps {
                echo 'Docker Image Push'
                script {
                    // cleanup currunt user docker credentials
                    sh 'rm -f ~/.dockercfg ~/.docker/config.json || true'
                    
                    sh 'aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 257307634175.dkr.ecr.ap-northeast-2.amazonaws.com'
                    sh 'docker tag std04-spring-petclinic:1.0 257307634175.dkr.ecr.ap-northeast-2.amazonaws.com/std04-spring-petclinic:1.0'
                    sh 'docker push 257307634175.dkr.ecr.ap-northeast-2.amazonaws.com/std04-spring-petclinic:1.0'
                    
                }
            }
        }
    
        stage("deploy") {
            steps {
                echo 'Deploy'
                
                
            }
        }
    }
}
