pipeline {
    agent any
    
    tools {
        maven 'M3'
        jdk 'JDK11'
    }
    
    enviroment {
        AWS_CREDENTIAL_NAME = "awsEcrCredentials"
        REGION = "ap-northeast-2"
        ECR_REPOSITORY = "257307634175.dkr.ecr.ap-northeast-2.amazonaws.com"
        ECR_DOCKER_IMAGE = "std04-spring-petclinic/spring-petclinic"
        ECR_DOCKER_TAG = "1.0"
    }
    
    
    stages {
        stage("git init") {
            steps {
                echo 'Git Init'
                git url:'https://github.com/JafarKim/spring-petclinic.git/',
                branch: 'main', credentialsId: 'gitCredentials'
            }
        }
        stage("build") {
            steps {
                echo 'Build'
                sh 'mvn -Dmaven.test.failure.ignore=true clean package'
            }
        }
        stage("docker image build") {
            steps {  
                echo 'Docker Image Build'
                dir("${env.WORKSPACE}") {
                    sh 'docker build -t ${ECR_DOCKER_IMAGE}:${ECR_DOCKER_TAG} .'
                }
            }
        }
        stage ("docker image push") {
            steps {
                echo 'Docker Image Push'
                script {
                    // cleanup currunt user docker credentials
                    sh 'rm -f ~/.dockercfg ~/.docker/config.json || true'
                    
                    docker.withRegistry("https://${ECR_REPOSITORY}", "ecr:${REGION}:${AWS_CREDENTIAL_NAME}") {
                        docker.image("${ECR_DOCKER_IAMGE}:${ECR_DOCKER_TAG}").push()
                    }
                }
            }
        }
    
        stage("deploy") {
            steps {
                echo 'Deploy'
                
                
            }
        }
    }
}
